### ISSUE TITLE
Warning on compile

### ISSUE THREAD

**Issue by ruggb** [olikraus/u8glib#366]
I am using Adruino 1.6.5 and Marlin RC2 and the updated version of u8glib - 1.14
I get this warming when I compile
--
d:\Users\Bill\Documents\Arduino\libraries\U8glib\src\clib\u8g_rot.c:48:1: warning: initialization from incompatible pointer type [enabled by default]

 u8g_dev_t u8g_dev_rot = { u8g_dev_rot_dummy_fn, NULL, NULL };

 ^

d:\Users\Bill\Documents\Arduino\libraries\U8glib\src\clib\u8g_rot.c:48:1: warning: (near initialization for 'u8g_dev_rot.dev_fn') [enabled by default]
--
and I have no Idea why there is large font in this post - some text copied from compile window

**Comment by olikraus** [comment]
The warning can be ignored, but yes, it should be fixed once.

**Comment by mickkn** [comment]
If you replace 
uint8_t u8g_dev_rot_dummy_fn(void *u8g, void *dev, uint8_t msg, void *arg)
{
	return 0;
}

with
#ifdef __XC8
uint8_t u8g_dev_rot_dummy_fn(void *u8g, void *dev, uint8_t msg, void *arg)
{
	return 0;
}
#else
uint8_t u8g_dev_rot_dummy_fn(u8g_t *u8g, u8g_dev_t *dev, uint8_t msg, void *arg)
{
	return 0;
}
#endif

the warning disappears

**Comment by olikraus** [comment]
actualy, i have not yet investigated this. But i also do see the warning.

Oliver

**Comment by olikraus** [comment]
fixed

**Comment by bolsoncerrado** [comment]
Just landed here after googleing 

"warning: initialization from incompatible pointer type
 u8g_dev_t u8g_dev_rot = { u8g_dev_rot_dummy_fn, NULL, NULL };"


I still have this issue on Arduino IDE 1.6.12 and u8glib u8glib_arduino_v1.18.1.zip


Is this normal?


Thanks!

**Comment by olikraus** [comment]
Yes, it is fixed in U8g2.

**Comment by bolsoncerrado** [comment]
Oh I thought I downloaded the most current version yesterday? I was wrong or is 2.0 not yet released?

**Comment by jhkim1327** [comment]
> If you replace
> uint8_t u8g_dev_rot_dummy_fn(void *u8g, void *dev, uint8_t msg, void *arg)
> {
> return 0;
> }
> 
> with
> #ifdef __XC8
> uint8_t u8g_dev_rot_dummy_fn(void *u8g, void *dev, uint8_t msg, void *arg)
> {
> return 0;
> }
> #else
> uint8_t u8g_dev_rot_dummy_fn(u8g_t *u8g, u8g_dev_t *dev, uint8_t msg, void *arg)
> {
> return 0;
> }
> #endif
> 
> the warning disappears

Many Thanks! 

it works! fixed!! Thanks a lot :)

**Comment by kpdelucia** [comment]
I am not that adept at arduino library manipulation.  when I open the new Marlin 2.0 It only loads Marlin configuration .h and configuration adv.h   Is the edit above supposed to be performed by opening u8glib.h?  I cant open it from arduino.  I can choose add file then add the u8glib.h  but i cannot find the lines you say need correction.  Where do i find the "uint8_t u8g_dev_rot_dummy_fn(void *u8g, void *dev, uint8_t msg, void *arg)" to be replaced?

Thanks
